### ISSUE TITLE
[PE-D] Users should be able to add a recipe with no ingredients and update it later.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T16-3/tp#100]
![image.png](https://raw.githubusercontent.com/aditichadha1310/ped/main/files/e7f3e15b-e5de-4476-8de3-7ff571fde17c.png)
Users should be given the choice to add a recipe without the ingredients. The user should be able to add ingredients later because inserting **recipe name + ingredients with quantity** at one time becomes a very long command. It gets tough for the user to keep a track of it as the number of the ingredients increase. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: aditichadha1310/ped#3

**Comment by vincentlauhl** [comment]
Update recipe will be changed to allow users to add/remove ingredients in the recipe. Recipe should be added with at least one ingredient, and a recipe must always have at least one ingredient.
