### ISSUE TITLE
[PE-D] /u can be an Integer

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T16-3/tp#102]
For commands that use the '/u' parameter (meaning units), integers can be used, making results like '0 6 of Chicken' possible, where '6' is the unit.

![error1.PNG](https://raw.githubusercontent.com/YipWayne/ped/main/files/27b9c60e-0798-4ccf-a09a-8f6b5ac07dac.PNG)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: YipWayne/ped#1

**Comment by JoshHDs** [comment]
Will modify u/ parameter to take in only letters and no integers.
