### ISSUE TITLE
[PE-D] expire date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T16-3/tp#95]
![image.png](https://raw.githubusercontent.com/xingyuan123/ped/main/files/71c91175-fb7f-425c-8580-b729e5fcbcca.png)

shouldnt it be after?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: xingyuan123/ped#3

**Comment by bernardboey** [comment]
Our documentation is correct ("before" is correct). To make it clearer, we will give an example of an expired vs unexpired expiry date.
