### ISSUE TITLE
[PE-D] Unable to use this command to view recipes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T16-3/tp#99]
Unable to use this command to view recipes

![Screenshot 2021-10-29 at 5.11.28 PM.png](https://raw.githubusercontent.com/arcturusz/ped/main/files/38ae6ff9-c9fb-426f-9cce-a258bc49ddbd.png)

![image.png](https://raw.githubusercontent.com/arcturusz/ped/main/files/450cf7a3-3626-4556-8868-cbe63c5a0ded.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: arcturusz/ped#4

**Comment by vincentlauhl** [comment]
Bug fixed.
